### ISSUE TITLE
Ability to disable line highlight

### ISSUE THREAD

**Issue by burhanuday** [krzysztofzuraw/writer-mode#39]
I would like to disable the line highlight feature displayed below
<img width="874" alt="image" src="https://user-images.githubusercontent.com/25934701/148964486-a8a71815-cc8b-4fca-b258-dbbf823aadda.png">

it is very distracting while writing. is it possible to do so?

**Comment by kzuraw** [comment]
Hi,
It should be possible by changing default override settings:
```json
"writerMode.overrideSettings": {
  "editor.fontSize": 20,
  "editor.rulers": [],
  "editor.renderLineHighlight": "none",
}
```

**Comment by burhanuday** [comment]
@krzysztofzuraw the extension overrides the settings.json in the .vscode folder. how would i go on changing this so that the extension does not override this?

**Comment by burhanuday** [comment]
I finally understood what you meant. for anyone else who has come here for the same. you can override the settings by editing the `settings.json` file 
```json
{
  "editor.fontSize": 12,
  "editor.rulers": [],
  "editor.renderLineHighlight": "none",
  "workbench.colorCustomizations": {},
  "writerMode.overrideSettings": {
    "editor.fontSize": 20,
    "editor.rulers": [],
    "editor.renderLineHighlight": "none"
  }
}

```
